name: Action CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build and Update Mappings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Update Mappings
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update mappings